name: Assign new issues to the default project
on:
  issues:
    types: [ opened, reopened ]
jobs:
  assign:
    name: Assign to project
    runs-on: ubuntu-latest
    steps:
      - name: Assign to project
        uses: zeebe-io/project-action@0.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.PROJECT_ADMIN_TOKEN }}
        with:
          project_type: "org"
          project_owner: "camunda"
          project_name: "Zeebe"
